openapi: 3.0.0
info:
  title: Sample API
  description: サンプルのAPIです。
  version: 1.0.0

servers:
- url: https://development.gigantic-server.com/v1
  description: Development server
- url: https://staging.gigantic-server.com/v1
  description: Staging server
- url: https://api.gigantic-server.com/v1
  description: Production server

components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string

externalDocs:
  description: "SampleAPIについて詳しく"
  url: "http://google.jp"